Inventory/Models/Inventory/ReturStokViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Inventory.Models.Inventory
{
    public class ReturStokViewModel
    {
        public DateTime Tanggal { get; set; }
        public int Supplier { get; set; }
        public int Lokasi { get; set; }
        public string Keterangan { get; set; }
        public decimal PPN { get; set; }
        public bool IncludePPN { get; set; }
        public decimal TotalNilai { get; set; }
        public List<ReturStokDetailViewModel> Detail { get; set; }
    }

    public class ReturStokDetailViewModel 
    {
        public int Id { get; set; }
        public int Qty { get; set; }
        public decimal Harga { get; set; }
    }
}

Inventory/Controllers/Inventory/ReturStokController.cs
using Inventory.Entities.SIM;
using Inventory.Helper;
using Inventory.Models.Inventory;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using System.Xml;

namespace Inventory.Controllers.Inventory
{
    [Authorize(Roles = "Inventory")]
    public class ReturStokController : Controller
    {
        private string tipepelayanan = "GUDANG";

        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan) return HttpNotFound();
            return View();
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                if (Request.Cookies["Inventory_Section_LokasiId"] == null) throw new Exception("Lokasi Id tidak ditemukan");
                var lokasi = int.Parse(Request.Cookies["Inventory_Section_LokasiId"].Value);

                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_ListReturStok.Where(x => x.Lokasi_ID == lokasi).AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                        {
                            proses = proses.Where(y =>
                                y.No_Retur.Contains(x.Value) ||
                                y.Keterangan.Contains(x.Value) ||
                                y.Nama_Supplier.Contains(x.Value));
                        }
                        else if (x.Key == "PeriodeStart" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tgl_Retur >= d);
                        }
                        else if (x.Key == "PeriodeEnd" && !string.IsNullOrEmpty(x.Value))
                        {
                            var d = DateTime.Parse(x.Value);
                            proses = proses.Where(y => y.Tgl_Retur <= d);
                        }
                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Tanggal = m.Tgl_Retur.ToString("dd/MM/yyyy"),
                        No = m.No_Retur,
                        Supplier = m.Nama_Supplier,
                        Keterangan = m.Keterangan
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, ReturStokViewModel model)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan) return HConvert.Error("Bukan Tipe Pelayanan");
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        var userid = User.Identity.GetUserId();
                        string id = "";
                        if (_process == "CREATE")
                        {
                            //if (model.Detail == null) model.Detail = new List<ReturStokDetailViewModel>();
                            //if (model.Detail.Count == 0) throw new Exception("Detail tidak boleh kosong");
                            //var model_id = s.INV_InsertReturObat(
                            //    model.Tanggal,
                            //    model.Keterangan,
                            //    model.Supplier,
                            //    model.Lokasi
                            //).FirstOrDefault();
                            //if (model_id == null) throw new Exception("INV_InsertReturStok tidak mendapatkan nobukti");
                            //id = model_id.NoRetur;

                            //foreach (var x in model.Detail)
                            //{
                            //    if (x.Qty <= 0) throw new Exception("Qty tidak boleh kurang dari sama dengan 0");
                            //    if (x.Harga <= 0) throw new Exception("Harga tidak boleh kurang dari sama dengan 0");
                            //    s.INV_InsertReturObatDetail(
                            //        (int)model_id.ID,
                            //        x.Harga,
                            //        x.Id,
                            //        x.Qty,
                            //        model.Lokasi,
                            //        model_id.NoRetur
                            //    );
                            //}
                            s.SaveChanges();
                        }

                        var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                        {
                            Activity = $"Penerimaan-{_process}; id:{id};".ToLower()
                        };
                        UserActivity.InsertUserActivity(userActivity);
                        dbContextTransaction.Commit();

                        return JsonConvert.SerializeObject(new { IsSuccess = true, Id = id });
                    }
                    catch (SqlException ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                    catch (Exception ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                }
            }
        }

        [HttpPost]
        public string Detail(string id)
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan) return HConvert.Error("Bukan Tipe Pelayanan");
            try
            {
                using (var s = new SIMEntities())
                {
                    var m = s.INV_ListReturStokHeader.FirstOrDefault(x => x.No_Retur == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    var d = s.INV_ListReturStokDetail.Where(x => x.Retur_ID == m.Retur_ID).OrderBy(x => x.Nama_Barang).ToList();
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            No = m.No_Retur,
                            Tanggal = m.Tgl_Retur.ToString("yyyy-MM-dd"),
                            Supplier = m.Supplier_ID,
                            Lokasi = m.Lokasi_ID,
                            Keterangan = m.Keterangan
                        },
                        Detail = d.ConvertAll(x => new
                        {
                            Id = x.Barang_ID,
                            Kode = x.Kode_Barang,
                            Nama = x.Nama_Barang,
                            Konversi = x.Konversi,
                            Satuan = x.NamaSatuan,
                            Qty = x.Qty_Retur,
                            Harga = x.Harga_Retur,
                        })
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== L O O K U P

        [HttpPost]
        public string ListLookupBarang(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan) return HConvert.Error("Bukan Tipe Pelayanan");
                var lokasi = int.Parse(Request.Cookies["Inventory_Section_LokasiId"].Value);

                int totalcount;
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_LookupBarang.Where(x => x.Lokasi_ID == lokasi).AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y =>
                                y.Nama_Barang.Contains(x.Value) ||
                                y.Kategori.Contains(x.Value));
                        else if (x.Key == "Lokasi")
                        {
                            var _v = int.Parse(x.Value);
                            proses = proses.Where(y => y.Lokasi_ID == _v);
                        }
                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        Id = x.Barang_ID,
                        Kode = x.Kode_Barang,
                        Nama = x.Nama_Barang,
                        Konversi = x.Konversi,
                        Satuan = x.Satuan,
                        Stok = x.Qty_Stok,
                        Kategori = x.Kategori,
                        MinStok = x.Min_Stok,
                        MaxStok = x.Max_Stok,
                        QtyStok = x.Qty_Stok,
                        Harga = x.Harga_Beli
                    });

Inventory/Controllers/ReportController.cs
using Inventory.Helper;
using Inventory.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class ReportController : Controller
    {
        private string serverpath = "~/Reports/";

        public ActionResult Index(string name, string category)
        {
            var hreport = new HReport(Server, serverpath);
            var r = new ReportInventoryViewModel();
            r.Name = name;
            r.Category = category;
            r.Reports = hreport.List(r.Category);
            return View(r);
        }

        public ActionResult ExportPDF(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportPDF(server, database, user, pass, category, filename, parameters);
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/pdf");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult ExportExcel(string category, string filename, string param)
        {
            try
            {
                var server = WebConfigurationManager.AppSettings["reportserver"];
                var database = WebConfigurationManager.AppSettings["reportdatabase"];
                var user = WebConfigurationManager.AppSettings["reportuser"];
                var pass = WebConfigurationManager.AppSettings["reportpass"];

                var hreport = new HReport(Server, serverpath);
                var parameters = JsonConvert.DeserializeObject<List<HReportParameter>>(param);
                var stream = hreport.ExportExcel(server, database, user, pass, category, filename, parameters);
                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();
                return File(stream, "application/vnd.ms-excel");
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

Inventory/Views/ReturStok/Index.cshtml
@{
    ViewBag.Title = "Retur Stok";
    ViewBag.breadcrumb = new List<SelectListItem>()
{
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}
@using Inventory.Helper
@using Microsoft.AspNet.Identity

<style>
    #formtable table th,
    #formtable table td {
        white-space: nowrap;
    }
</style>

<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <div class="panel-title"></div>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>
                    <li><a class="panel-action action-filter" href="javascript:itable.openfilter()"></a></li>
                </ul>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-2">
                <label>Filter</label>
                <input type="text" name="all" data-itable-filter="All" class="form-control" />
            </div>
            <div class="col-md-2">
                <label>Dari Tanggal</label>
                <input type="date" name="periode" onchange="itable.pageindex = 0; itable.refresh();" data-itable-filter="PeriodeStart" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            <div class="col-md-2">
                <label>Sampai Tanggal</label>
                <input type="date" name="sampai" onchange="itable.pageindex = 0; itable.refresh();" data-itable-filter="PeriodeEnd" class="form-control" value="@(DateTime.Today.ToString("yyyy-MM-dd"))" />
            </div>
            @*<label class="control-label col-md-2">Show</label>*@
            <div class="col-md-1">
                <label>Page</label>
                <select class="form-control itable-pagesize" onchange="itable.pageindex = 0; itable.refresh();" style="width: auto;" name="show">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>
            </div>
            <div class="col-md-2 hide">
                <button type="submit" style="margin-top : 27px" class="btn-save btn btn-primary"><i class="icon icon-search4"></i>Cari</button>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header">
                @*<input type="hidden" data-itable-filter="All" />
                <input type="hidden" data-itable-filter="PeriodeStart" value="@(ConfigModel.Develop ? "" : DateTime.Today.ToString("yyyy-MM-dd"))">
                <input type="hidden" data-itable-filter="PeriodeEnd" value="@(ConfigModel.Develop ? "" : DateTime.Today.ToString("yyyy-MM-dd"))">*@
                @*<select class="form-control itable-pagesize hide" style="width: auto;">
                    <option selected>10</option>
                    <option>25</option>
                    <option>50</option>
                    <option>100</option>
                </select>*@
            </div>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr>
                            <th class="sorting" data-itable-sorting="No_Retur" style="width: 100px;">No Retur<i></i></th>
                            <th class="sorting" data-itable-sorting="Tgl_Retur" style="width: 100px;">Tanggal<i></i></th>
                            <th class="sorting" data-itable-sorting="Nama_Supplier">Supplier<i></i></th>
                            <th class="sorting" data-itable-sorting="Keterangan">Keterangan<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<div id="modalfilter" class="modal fade" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <form autocomplete="off" onsubmit="itable.filtersubmit(this,event)">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Filter</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-md-4">Filter</label>
                            <div class="col-md-8">
                                <input type="text" name="all" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Periode</label>
                            <div class="col-md-8">
                                <input type="date" name="periode" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Sampai</label>
                            <div class="col-md-8">
                                <input type="date" name="sampai" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Show</label>
                            <div class="col-md-8">
                                <select class="form-control" style="width: auto;" name="show">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="icon icon-check"></i> OK</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'No_Retur',
            orderbytype: false,
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="5" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        tbody += '<tr class="alpha-' + status + '">';

                        // column
                        tbody += '<td>' + value.No + '</td>';
                        tbody += '<td class="text-center">' + value.Tanggal + '</td>';
                        tbody += '<td>' + value.Supplier + '</td>';
                        tbody += '<td>' + (value.Keterangan || '-') + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        tbody += '<li><a href="javascript:isetup.opensetup(\'VIEW\', { id : \'' + value.No + '\'})"><i class="icon-eye"></i> View</a></li>';
                        tbody += '<li><a target="_blank" href="@Url.Action("ExportPDF", "Report", new { category = "Transaksi", filename= "SIM_Rpt_ReturStok.rpt" })&param=[{\'Name\':\'@@NoBukti\',\'ParameterType\':4,\'Value\':\'' + value.No + '\'}]"><i class="icon-printer"></i> Report</a></li>';

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });

        itable.refresh();

        itable.openfilter = function () {
            var f = $('#modalfilter form')[0];
            f['periode'].value = $('#formtable [data-itable-filter="PeriodeStart"]')[0].value;
            f['sampai'].value = $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value;
            f['all'].value = $('#formtable [data-itable-filter="All"]')[0].value;
            f['show'].value = $('#formtable .itable-pagesize')[0].value;
            $('#modalfilter').modal();
        }

        itable.filtersubmit = function (t, e) {
            e.preventDefault();
            var f = $('#modalfilter form')[0];
            $('#formtable [data-itable-filter="PeriodeStart"]')[0].value = f['periode'].value;
            $('#formtable [data-itable-filter="PeriodeEnd"]')[0].value = f['sampai'].value;
            $('#formtable [data-itable-filter="All"]')[0].value = f['all'].value;
            $('#formtable .itable-pagesize')[0].value = f['show'].value;
            itable.pageindex = 0;
            itable.refresh();
            $('#modalfilter').modal('hide');
        }
    });
</script>
@Html.Partial("Setup")
@Html.Partial("_LookUpBarang")

Inventory/Views/ReturStok/_LookUpBarang.cshtml
<style>
    #modallookupbarang .table td,
    #modallookupbarang .table th {
        white-space: nowrap;
    }
</style>

<div id="modallookupbarang" class="modal fade" role="dialog" style="z-index:1060;">
    <div class="modal-dialog modal-full">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Barang</h4>
            </div>
            <form id="lookupbarang">
                <div class="dataTables_wrapper no-footer" style="display: block;">
                    <div class="datatable-header">
                        <input type="hidden" data-itable-filter="Lokasi">
                        <div class="dataTables_filter">
                            <label>
                                <span>Filter:</span>
                                <input type="search" data-itable-filter="All" data-itable-filter-type="contains" placeholder="Type to filter...">
                            </label>
                        </div>
                        <div class="hide">
                            <label>
                                <span>Show:</span>
                                <select class="form-control itable-pagesize" style="width: auto;">
                                    <option selected>10</option>
                                    <option>25</option>
                                    <option>50</option>
                                    <option>100</option>
                                </select>
                            </label>
                        </div>
                    </div>
                    <div class="datatable-scroll table-responsive">
                        <table class="table datatable-basic dataTable no-footer table-xxs table-striped table-lookup">
                            <thead>
                                <tr>
                                    <th class="sorting" data-itable-sorting="Kode_Barang">Kode<i></i></th>
                                    <th class="sorting" data-itable-sorting="Nama_Barang">Nama<i></i></th>
                                    <th class="sorting" data-itable-sorting="Qty_Stok">Stok<i></i></th>
                                    <th class="sorting" data-itable-sorting="Kategori">Kategori<i></i></th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <div class="datatable-footer">
                        <div class="dataTables_info itable-info"></div>
                        <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
                    </div>
                </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn-save btn btn-primary" onclick="itablelookupbarang.selected(this)"><i class="glyphicon icon-check"></i> SELECT</button>
            </div>
        </div>
    </div>
</div>

<script>
    var itablelookupbarang;
    document.addEventListener("DOMContentLoaded", function (event) {
        itablelookupbarang = new iTable({
            url: '@Url.Action("ListLookupBarang")',
            table: document.getElementById('lookupbarang'),
            orderby: 'Kode_Barang',
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    $(t.table).find('tbody').html('');
                    let tbody = '';
                    if (r.Data.length === 0)
                        $(t.table).find('tbody').append('<tr><td colspan="6" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>');
                    $.each(r.Data, function (index, value) {
                        var tbody = '<tr class="odd" onclick="itablelookupbarang.active(this)">';

                        // column
                        tbody += '<td>' + value.Kode + '</td>';
                        tbody += '<td>' + value.Nama + '</td>';
                        tbody += '<td class="text-center">' + value.Stok + '</td>';
                        tbody += '<td>' + value.Kategori + '</td>';

                        tbody += '</tr>';
                        $(t.table).find('tbody').append(tbody);
                        $(t.table).find('tbody tr').last().data('model', JSON.stringify(value));
                    });
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else alert(r.Message);
            }
        });

        $('#modallookupbarang').on('hidden.bs.modal', function () {
            $('body').addClass('modal-open');
        });
        $('#modallookupbarang').on('shown.bs.modal', function (e) {
             $('#modallookupbarang [data-itable-filter="All"]').focus();
        });

        itablelookupbarang.active = (t) => {
            $(t).toggleClass('bg-primary');
        }

        itablelookupbarang.openmodal = () => {
            $('#modallookupbarang [data-itable-filter="Lokasi"]').val('@Request.Cookies["Inventory_Section_LokasiId"].Value');
            itablelookupbarang.pageindex = 0;
            itablelookupbarang.refresh();
            $('#modallookupbarang').modal();
            $('.modal-backdrop:last').css('z-index', $('#modallookupbarang').css('z-index') - 1);
        }

        itablelookupbarang.selected = function (t) {
            $.each($(t).closest('.modal').find('table tbody tr.bg-primary'), function (index, value) {
                var model = JSON.parse($(value).data('model'));

                isetup.adddetailbody(
                    model.Id,
                    model.Kode,
                    model.Nama,
                    model.Satuan,
                    model.Konversi,
                    1,
                    model.Harga,
                    0
                );
            });
            $(t).closest('.modal').modal('hide');
        }
    });
</script>