Inventory/Controllers/Inventory/SetupSubKategoriBarangController.cs
using Inventory.Entities.SIM;
using Inventory.Helper;
using Inventory.Models.Inventory;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers.Inventory
{
    [Authorize(Roles = "Inventory")]
    public class SetupSubKategoriBarangController : Controller
    {
        private string tipepelayanan = "GUDANG";

        #region ===== L I S T

        [HttpGet]
        public ActionResult Index()
        {
            if (Request.Cookies["Inventory_Section_Group"].Value != tipepelayanan) return HttpNotFound();
            return View();
        }

        [HttpPost]
        public string List(string orderby, bool orderbytype, int pagesize, int pageindex, List<FilterModel> filter)
        {
            try
            {
                int totalcount;
                using (var s = new SIMEntities())
                {
                    var userid = User.Identity.GetUserId();
                    var proses = s.INV_mSubKategori.AsQueryable();
                    foreach (var x in filter)
                    {
                        if (x.Key == "All" && !string.IsNullOrEmpty(x.Value))
                            proses = proses.Where(y => y.Kode_Sub_Kategori.Contains(x.Value) ||
                                y.Nama_Sub_Kategori.Contains(x.Value) ||
                                y.Nama_Kategori.Contains(x.Value));
                    }
                    totalcount = proses.Count();
                    var models = proses.OrderBy($"{orderby} {(orderbytype ? "ASC" : "DESC")}").Skip((pageindex) * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(x => new
                    {
                        Id = x.SubKategori_ID,
                        Kode = x.Kode_Sub_Kategori,
                        Kategori = x.Nama_Kategori,
                        Nama = x.Nama_Sub_Kategori
                    });
                    return JsonConvert.SerializeObject(new { IsSuccess = true, Data = r, TotalCount = totalcount });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion

        #region ===== S E T U P

        [HttpPost]
        public string Save(string _process, SetupSubKategoriBarangModel model)
        {
            using (var s = new SIMEntities())
            {
                using (var dbContextTransaction = s.Database.BeginTransaction())
                {
                    try
                    {
                        var userid = User.Identity.GetUserId();
                        var id = 0;
                        if (_process == "CREATE")
                        {
                            id = s.INV_InsertSubKategoriBarang(model.Kode, model.Nama, model.Kategori);
                            s.SaveChanges();
                        }
                        else if (_process == "EDIT")
                        {
                            s.INV_UpdateSubKategoriBarang(model.Kode, model.Nama, model.Kategori, model.Id);
                            s.SaveChanges();
                            id = model.Id;
                        }

                        var userActivity = new UserActivityModel(Request, User.Identity.GetUserId())
                        {
                            Activity = $"SetupSubKategoriBarang-{_process}; id:{id};".ToLower()
                        };
                        UserActivity.InsertUserActivity(userActivity);
                        dbContextTransaction.Commit();
                    }
                    catch (SqlException ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                    catch (Exception ex) { dbContextTransaction.Rollback(); return HConvert.Error(ex); }
                }
            }
            return HConvert.Success();
        }

        [HttpPost]
        public string Detail(int id)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var userid = User.Identity.GetUserId();

                    var m = s.INV_mSubKategori.FirstOrDefault(x => x.SubKategori_ID == id);
                    if (m == null) throw new Exception("Data tidak ditemukan");
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = new
                        {
                            Id = m.SubKategori_ID,
                            Kategori = m.Kategori_ID,
                            KategoriNama = $"{m.Kode_Kategori} - {m.Nama_Kategori}",
                            Kode = m.Kode_Sub_Kategori,
                            Nama = m.Nama_Sub_Kategori
                        }
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        #endregion
    }
}

Inventory/Controllers/Select2Controller.cs
using Inventory.Entities.SIM;
using Inventory.Helper;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inventory.Controllers
{
    public class Select2Controller : Controller
    {
        [HttpPost]
        public string Supplier(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    IQueryable<INV_GetSupplier> proses = s.INV_GetSupplier;
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Supplier.Contains(filter) ||
                            x.Nama_Supplier.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Supplier_ID,
                        Kode = m.Kode_Supplier,
                        Nama = m.Nama_Supplier
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Kode_Supplier(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    IQueryable<INV_GetSupplier> proses = s.INV_GetSupplier;
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Supplier.Contains(filter) ||
                            x.Nama_Supplier.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kode_Supplier,
                        Kode = m.Kode_Supplier,
                        Nama = m.Nama_Supplier
                    });
                    //r.Add();
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Supplier_Permintaan(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var lokasilogin = "";
                    if (Request.Cookies["Inventory_Section_Id"].Value == "SEC081")
                    {
                        lokasilogin = "V-007";
                    }
                    else if (Request.Cookies["Inventory_Section_Id"].Value == "SEC107")
                    {
                        lokasilogin = "V-006";
                    }
                    else
                    {
                        lokasilogin = "";
                    }

                    if (filter == null) {
                        filter = " ";
                    }
                    IQueryable<INV_ListSupplier> proses = s.INV_ListSupplier;
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                        x.Kode_Kategori.Contains(filter) ||
                        x.Nama_Supplier.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Supplier).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Supplier_ID,
                        Kode = m.Kode_Supplier,
                        Nama = m.Nama_Supplier
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string Kategori(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    IQueryable<mKategori_Vendor> proses = s.mKategori_Vendor;
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Kategori.Contains(filter) ||
                            x.Kategori_Name.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Kategori).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kode_Kategori,
                        Kode = m.Kode_Kategori,
                        Nama = m.Kategori_Name
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }
        [HttpPost]
        public string KategoriBarang(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    IQueryable<INV_mKategori> proses = s.INV_mKategori;
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Kategori.Contains(filter) ||
                            x.Nama_Kategori.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Kategori).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kode_Kategori,
                        Kode = m.Kode_Kategori,
                        Nama = m.Nama_Kategori
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        [HttpPost]
        public string SetupSubKategoriBarangKategori(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_mKategori.AsQueryable();
                    if (!string.IsNullOrEmpty(filter))
                    {
                        proses = proses.Where(x =>
                            x.Kode_Kategori.Contains(filter) ||
                            x.Nama_Kategori.Contains(filter)
                        );
                    }
                    var totalcount = proses.Count();
                    var models = proses.OrderBy(x => x.Kode_Kategori).Skip(pageindex * pagesize).Take(pagesize).ToList();
                    var r = models.ConvertAll(m => new
                    {
                        Id = m.Kategori_ID,
                        Kode = m.Kode_Kategori,
                        Nama = m.Nama_Kategori
                    });
                    return JsonConvert.SerializeObject(new
                    {
                        IsSuccess = true,
                        Data = r,
                        TotalCount = totalcount,
                        PageIndex = pageindex,
                    });
                }
            }
            catch (SqlException ex) { return HConvert.Error(ex); }
            catch (Exception ex) { return HConvert.Error(ex); }
        }

        public string SetupSubKategoriStokOpname(int pagesize, int pageindex, string filter)
        {
            try
            {
                using (var s = new SIMEntities())
                {
                    var proses = s.INV_mSubKategori.AsQueryable();

                    if (!string.IsNullOrEmpty(filter))

Inventory/Views/SetupSubKategoriBarang/Index.cshtml
@{
    ViewBag.Title = "Sub Kategori Barang";
    ViewBag.breadcrumb = new List<SelectListItem>()
    {
        new SelectListItem(){ Text = ViewBag.Title, Value = "active" }
    };
}

<form id="formtable">
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title"></h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a class="panel-action action-plus" href="javascript:isetup.opensetup('CREATE')"></a></li>
                    <li><a class="panel-action action-reload" href="javascript:itable.refresh()"></a></li>
                </ul>
            </div>
        </div>
        <div class="dataTables_wrapper no-footer" style="display: block;">
            <div class="datatable-header">
                <div class="dataTables_filter">
                    <label>
                        <span>Filter:</span>
                        <input type="search" data-itable-filter="All" data-itable-filter-type="contains" placeholder="Type to filter...">
                    </label>
                </div>
                <div class="dataTables_length">
                    <label>
                        <span>Show:</span>
                        <select class="form-control itable-pagesize" style="width: auto;">
                            <option selected>10</option>
                            <option>25</option>
                            <option>50</option>
                            <option>100</option>
                        </select>
                    </label>
                </div>
            </div>
            <div class="datatable-scroll">
                <table class="table datatable-basic dataTable no-footer table-xxs table-striped">
                    <thead>
                        <tr>
                            <th class="sorting" data-itable-sorting="Kode_Sub_Kategori" style="width:100px;">Kode<i></i></th>
                            <th class="sorting" data-itable-sorting="Nama_Sub_Kategori">Nama<i></i></th>
                            <th class="sorting" data-itable-sorting="Nama_Kategori">Kategori<i></i></th>
                            <th class="text-center sorting_disabled" style="width: 100px;">Actions</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="datatable-footer">
                <div class="dataTables_info itable-info"></div>
                <div class="dataTables_paginate paging_simple_numbers itable-pagination"></div>
            </div>
        </div>
    </div>
</form>

<script>
    var itable;
    document.addEventListener("DOMContentLoaded", function (event) {
        itable = new iTable({
            url: '@Url.Action("List")',
            table: document.getElementById('formtable'),
            orderby: 'Kode_Sub_Kategori',
            tablesuccess: function (r, t) {
                if (r.IsSuccess) {
                    var tbody = '';
                    if (r.Data.length === 0)
                        tbody += '<tr><td colspan="4" class="text-center">----- <b>Tidak ada data</b> -----</td></tr>';
                    $.each(r.Data, function (index, value) {
                        tbody += '<tr class="odd">';

                        // column
                        tbody += '<td>' + value.Kode + '</td>';
                        tbody += '<td>' + value.Nama + '</td>';
                        tbody += '<td>' + (value.Kategori || '-') + '</td>';

                        tbody += '<td class="text-center">';
                        tbody += '<ul class="icons-list">';
                        tbody += '<li class="dropdown">';
                        tbody += '<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-menu9"></i></a>';
                        tbody += '<ul class="dropdown-menu dropdown-menu-right">';

                        // action
                        tbody += '<li><a href="javascript:isetup.opensetup(\'EDIT\',{ id : \'' + value.Id + '\'})"><i class="icon-pencil"></i> Edit</a></li>';

                        tbody += '</ul>';
                        tbody += '</li>';
                        tbody += '</ul>';
                        tbody += '</td>';
                        tbody += '</tr>';
                    });
                    $(t.table).find('tbody').html(tbody);
                    var footer = generatefootertable(r.TotalCount, t.pagesize, t.pageindex, 'tableordergetdatas');
                    $(t.table).find('.itable-info').html(footer.datainfo);
                    $(t.table).find('.itable-pagination').html(footer.pagination);
                } else {
                    alert(r.Message);
                }
            }
        });
        itable.refresh();
    });
</script>
@Html.Partial("Setup")

Inventory/Views/SetupSubKategoriBarang/Setup.cshtml
<div id="modalsetup" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Sub Kategori Barang</h4>
            </div>
            <form autocomplete="off">
                <div class="modal-body">
                    <div class="form-horizontal">
                        <input type="hidden" name="_PROCESS" />
                        <input type="hidden" name="Id" />
                        <div class="form-group">
                            <label class="col-md-2 control-label">Kode</label>
                            <div class="col-md-10">
                                <input type="text" required name="Kode" class="form-control" maxlength="100" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Nama</label>
                            <div class="col-md-10">
                                <input type="text" required name="Nama" class="form-control" maxlength="100" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Kategori</label>
                            <div class="col-md-10">
                                <select name="Kategori"></select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn-save btn btn-primary"><i class="glyphicon glyphicon-floppy-disk"></i> SAVE</button>
                    <button type="submit" class="btn-delete btn btn-danger"><i class="glyphicon glyphicon-trash"></i> DELETE</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    var isetup;
    document.addEventListener("DOMContentLoaded", function (event) {
        isetup = new iSetup({
            modal: 'modalsetup',
            urldetail: '@Url.Action("Detail")',
            urlsave: '@Url.Action("Save")',
            detailsuccess: function (r, proc) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    var t = isetup.form;

                    // detail value
                    t['Id'].value = r.Data.Id;
                    t['Nama'].value = r.Data.Nama;
                    t['Kategori'].value = r.Data.Kategori;
                    t['Kode'].value = r.Data.Kode;

                    var option = new Option(r.Data.KategoriNama, r.Data.Kategori, true, true);
                    $(t['Kategori']).append(option);
                    
                    isetup.init();
                    isetup.modal.modal({backdrop: 'static'});
                } else
                    alert(r.Message);
            },
            saveparam: function () {
                var t = isetup.form;
                return {
                    _process : t['_PROCESS'].value,
                    model: {

                        // param
                        Id: t['Id'].value,
                        Nama: t['Nama'].value,
                        Kategori: t['Kategori'].value,
                        Kode: t['Kode'].value,

                    }
                }
            },
            savesuccess: function (r) {
                r = JSON.parse(r);
                if (r.IsSuccess) {
                    isetup.modal.modal('hide');
                    itable.refresh();
                } else
                    alert(r.Message);
            },
            setupready: function () {
                var t = isetup.form;
                if (t['_PROCESS'].value === 'DELETE') $(t).find('[type="submit"].btn-danger').focus();
            },
            onopenmodalcreate: function (t) {
                isetup.form['Kategori'].value = '';
                isetup.init();
            }
        });

        $(isetup.form['Kategori']).select2({
            ajax: {
                url: "@Url.Action("SetupSubKategoriBarangKategori", "Select2")",
                dataType: 'json',type: "POST",delay: 250,
                data: function (params) {return {pagesize: 30,pageindex: params.page || 0,filter: params.term};},
                processResults: function (data, params) {
                    if (!data.IsSuccess) alertpopup(data.Message, 'danger');
                    else {
                        params.page = data.PageIndex + 1;
                        return { results: $.map(data.Data, function (value, indel) { return { id: value.Id, text:  value.Kode + ' - ' + value.Nama } }), pagination: { more: (params.page * 30) < data.TotalCount } };
                    }
                }, cache: true
            }
        });
    });
</script>